import { useNavigate } from "react-router-dom";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { ArrowLeft } from "lucide-react";

const sections = [
  {
    title: "Consent",
    content: "By using our website, you hereby consent to our Privacy Policy and agree to its terms.",
  },
  {
    title: "Information We Collect",
    content: `The personal information that you are asked to provide, and the reasons why you are asked to provide it, will be made clear to you at the point we ask you to provide your personal information.

If you contact us directly, we may receive additional information about you such as your name, email address, phone number, the contents of the message and/or attachments you may send us, and any other information you may choose to provide.

When you register for an Account, we may ask for your contact information, including items such as name, company name, address, email address, and telephone number.`,
  },
  {
    title: "How We Use Your Information",
    content: "We use the information we collect in various ways, including to:",
    bullets: [
      "Provide, operate, and maintain our website",
      "Improve, personalize, and expand our website",
      "Understand and analyze how you use our website",
      "Develop new products, services, features, and functionality",
      "Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the website, and for marketing and promotional purposes",
      "Send you emails",
      "Find and prevent fraud",
    ],
  },
  {
    title: "Log Files",
    content:
      "Our platform follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.",
  },
  {
    title: "Cookies and Web Beacons",
    content:
      "Like any other website, our platform uses 'cookies'. These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information.",
  },
  {
    title: "CCPA Privacy Rights (Do Not Sell My Personal Information)",
    content: "Under the CCPA, among other rights, California consumers have the right to:",
    bullets: [
      "Request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.",
      "Request that a business delete any personal data about the consumer that a business has collected.",
      "Request that a business that sells a consumer's personal data, not sell the consumer's personal data.",
    ],
    footer: "If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.",
  },
  {
    title: "GDPR Data Protection Rights",
    content: "We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:",
    bullets: [
      "The right to access — You have the right to request copies of your personal data.",
      "The right to rectification — You have the right to request that we correct any information you believe is inaccurate.",
      "The right to erasure — You have the right to request that we erase your personal data, under certain conditions.",
      "The right to restrict processing — You have the right to request that we restrict the processing of your personal data, under certain conditions.",
      "The right to object to processing — You have the right to object to our processing of your personal data, under certain conditions.",
      "The right to data portability — You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.",
    ],
  },
];

const terms = [
  "This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.",
  "This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of our platform, including the related mobile site and mobile application (hereinafter referred to as \"Platform\").",
  "The Platform is owned by Zeen Digital Solutions LLP, a company incorporated under the Companies Act, 1956 with its registered office (hereinafter referred to as \"Platform Owner\", \"we\", \"us\", \"our\").",
  "Your use of the Platform and services and tools are governed by the following terms and conditions (\"Terms of Use\") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference.",
  "For the purpose of these Terms of Use, wherever the context so requires \"you\", \"your\" or \"user\" shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.",
  "ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.",
];

export default function Terms() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <div className="pt-24 pb-16 px-4 sm:px-6 max-w-3xl mx-auto">

        <button
          onClick={() => navigate("/")}
          className="flex items-center gap-2 text-white/40 hover:text-white text-sm mb-8 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </button>

        {/* Header */}
        <div className="mb-8">
          <h1 className="legal-heading text-4xl sm:text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-amber-300 via-orange-300 to-red-400 mb-2">Terms and Conditions</h1>
          <p className="text-white/40 text-xs uppercase tracking-widest font-bold">Last Updated: 15-01-2026</p>
        </div>

        {/* Intro */}
        <div className="rounded-2xl border border-amber-500/20 bg-gradient-to-br from-amber-950/30 to-zinc-900/60 p-6 mb-5">
          <p className="legal-body mb-4">
            At Zeen Digital Solutions LLP, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by our platform and how we use it.
          </p>
          <p className="legal-body mb-4">
            If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.
          </p>
          <p className="legal-body">
            This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect on our platform. This policy is not applicable to any information collected offline or via channels other than this website.
          </p>
        </div>

        {/* Sections */}
        {sections.map((section) => (
          <div key={section.title} className="rounded-2xl border border-white/10 bg-zinc-900/60 p-6 mb-5">
            <h2 className="legal-heading text-sm font-bold text-transparent bg-clip-text bg-gradient-to-r from-amber-300 to-orange-400 mb-3">{section.title}</h2>
            {section.content && (
              <p className="legal-body whitespace-pre-line mb-3">{section.content}</p>
            )}
            {section.bullets && (
              <ul className="space-y-2 mb-3">
                {section.bullets.map((b) => (
                  <li key={b} className="flex items-start gap-2">
                    <span className="text-amber-400 mt-1 font-bold text-base leading-none">›</span>
                    <span className="legal-body">{b}</span>
                  </li>
                ))}
              </ul>
            )}
            {section.footer && (
              <p className="legal-body italic">{section.footer}</p>
            )}
          </div>
        ))}

        {/* Terms A–F */}
        <div className="rounded-2xl border border-amber-500/20 bg-gradient-to-br from-amber-950/20 to-zinc-900/60 p-6">
          <h2 className="legal-heading text-sm font-bold text-transparent bg-clip-text bg-gradient-to-r from-amber-300 to-orange-400 mb-4">Terms and Conditions</h2>
          <div className="space-y-4">
            {terms.map((term, i) => (
              <div key={i} className="flex items-start gap-3">
                <span className="text-amber-400 font-black text-sm flex-shrink-0 mt-1">
                  {String.fromCharCode(65 + i)}.
                </span>
                <p className={`legal-body ${i === 5 ? "text-white font-semibold italic" : ""}`}>
                  {term}
                </p>
              </div>
            ))}
          </div>
        </div>

      </div>
      <Footer />
    </div>
  );
}